name: Build iOS Geode Mod

on:
  workflow_dispatch:
  push:
    branches:
      - "**"
    tags:
      - "**"

jobs:
  build-ios:
    name: Build iOS
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build iOS mod
        id: build
        uses: geode-sdk/build-geode-mod@main
        with:
          target: iOS

      - name: Upload iOS build
        uses: actions/upload-artifact@v4
        with:
          name: CBFExtrapolate-iOS
          path: ${{ steps.build.outputs.build-output }}
          if-no-files-found: error
